spec: "1.0"
devices:
  device 1:
    eom:
      ASRL INSTR:
        q: "\r\n"
        r: "\n"
      USB INSTR:
        q: "\n"
        r: "\n"
      TCPIP INSTR:
        q: "\n"
        r: "\n"
      TCPIP SOCKET:
        q: "\n"
        r: "\n"
      GPIB INSTR:
        q: "\n"
        r: "\n"
    error: ERROR
    dialogues:
      - q: "?IDN"
        r: "LSG Serial #1234"
      - q: "!CAL"
        r: OK
    properties:
      frequency:
        default: 100.0
        getter:
          q: "?FREQ"
          r: "{:.2f}"
        setter:
          q: "!FREQ {:.2f}"
          r: OK
          e: 'FREQ_ERROR'
        specs:
          min: 1
          max: 100000
          type: float
      amplitude:
        default: 1.0
        getter:
          q: "?AMP"
          r: "{:.2f}"
        setter:
          q: "!AMP {:.2f}"
          r: OK
        specs:
          min: 0
          max: 10
          type: float
      offset:
        default: 0
        getter:
          q: "?OFF"
          r: "{:.2f}"
        setter:
          q: "!OFF {:.2f}"
          r: OK
        specs:
          min: 0
          max: 10
          type: float
      output_enabled:
        default: 0
        getter:
          q: "?OUT"
          r: "{:d}"
        setter:
          q: "!OUT {:d}"
          r: OK
        specs:
          valid: [0, 1]
          type: int
      waveform:
        default: 0
        getter:
          q: "?WVF"
          r: "{:d}"
        setter:
          q: "!WVF {:d}"
          r: OK
        specs:
          valid: [0, 1, 2, 3]
          type: int
  device 2:
    eom:
      ASRL INSTR:
        q: "\r\n"
        r: "\n"
      USB INSTR:
        q: "\n"
        r: "\n"
      TCPIP INSTR:
        q: "\n"
        r: "\n"
      GPIB INSTR:
        q: "\n"
        r: "\n"
    dialogues:
      - q: "*IDN?"
        r: "SCPI,MOCK,VERSION_1.0"
    error:
      status_register:
        - q: "*ESR?"
          command_error: 32
          query_error: 4
    properties:
      voltage:
        default: 1.0
        getter:
          q: ":VOLT:IMM:AMPL?"
          r: "{:+.8E}"
        setter:
          q: ":VOLT:IMM:AMPL {:.3f}"
        specs:
          min: 1
          max: 6
          type: float
      current:
        default: 1.0
        getter:
          q: ":CURR:IMM:AMPL?"
          r: "{:+.8E}"
        setter:
          q: ":CURR:IMM:AMPL {:.3f}"
        specs:
          min: 1
          max: 6
          type: float
      rail:
        default: P6V
        getter:
          q: "INST?"
          r: "{:s}"
        setter:
          q: "INST {:s}"
        specs:
            valid: ["P6V", "P25V", "N25V"]
            type: str
      output_enabled:
        default: 0
        getter:
          q: "OUTP?"
          r: "{:d}"
        setter:
          q: "OUTP {:d}"
        specs:
          valid: [0, 1]
          type: int
  device 3:
    eom:
      ASRL INSTR:
        q: "\r\n"
        r: "\n"
      USB INSTR:
        q: "\n"
        r: "\n"
      TCPIP INSTR:
        q: "\n"
        r: "\n"
      GPIB INSTR:
        q: "\n"
        r: "\n"
    dialogues:
      - q: "*IDN?"
        r: "SCPI,MOCK,VERSION_1.0"
    error:
      response:
        command_error: "INVALID_COMMAND"
      status_register:
        - q: "*ESR?"
          command_error: 32
          query_error: 4
    properties:
      voltage:
        default: 1.0
        getter:
          q: ":VOLT:IMM:AMPL?"
          r: "{:+.8E}"
        setter:
          q: ":VOLT:IMM:AMPL {:.3f}"
        specs:
          min: 1
          max: 6
          type: float
      current:
        default: 1.0
        getter:
          q: ":CURR:IMM:AMPL?"
          r: "{:+.8E}"
        setter:
          q: ":CURR:IMM:AMPL {:.3f}"
        specs:
          min: 1
          max: 6
          type: float
      read_only:
        default: P6V
        getter:
          q: "INST?"
          r: "{:s}"
      output_enabled:
        default: 0
        getter:
          q: "OUTP?"
          r: "{:d}"
        setter:
          q: "OUTP {:d}"
  device 4:
    eom:
      ASRL INSTR:
        q: "\r\n"
        r: "\n"
      USB INSTR:
        q: "\n"
        r: "\n"
      TCPIP INSTR:
        q: "\n"
        r: "\n"
      GPIB INSTR:
        q: "\n"
        r: "\n"
    dialogues:
      - q: "*IDN?"
        r: "SCPI,MOCK,VERSION_1.0"
    error:
      error_queue:
        - q: ':SYST:ERR?'
          default: '0, No Error'
          command_error: '1, Command error'
    properties:
      voltage:
        default: 1.0
        getter:
          q: ":VOLT:IMM:AMPL?"
          r: "{:+.8E}"
        setter:
          q: ":VOLT:IMM:AMPL {:.3f}"
        specs:
          min: 1
          max: 6
          type: float

  device 5:
    eom:
      ASRL INSTR:
        q: "\r\n"
        r: "\n"
      USB INSTR:
        q: "\r\n"
        r: "\n"
      TCPIP INSTR:
        q: "\r\n"
        r: "\n"
      TCPIP SOCKET:
        q: "\r\n"
        r: "\n"
      GPIB INSTR:
        q: "\r\n"
        r: "\n"
    error: ERROR
    dialogues:
      - q: "*IDN?"
        r: "HEWLETT-PACKARD, E3632A,0,1.2-5.0-1.0"
      - q: "SYST:ERR?"
        r: "NO ERROR"
      - q: "SOUR1:POW?"
        r: "2"
      - q: "READ1"
        r: "0.23 * ({amplitude} ** 2) - {frequency}"
        sources: [
          {name: "GPIB0::2::INSTR", parameter: amplitude},
          {name: "GPIB0::22::INSTR", parameter: frequency}
        ]
    properties:
      frequency:
        default: 1.0
        getter:
          q: "SENS1:FREQ?"
          r: "{:.2f}"
        setter:
          q: "SENS1:FREQ {:.2f} MHZ"
          r: ""
          e: "FREQ ERROR"
        specs:
          min: 0.0
          max: 27.0
          type: float
      current limit:
        default: 1.0
        getter:
          q: "MEAS:CURR?"
          r: "{:.2f}"
        setter:
          q: "CURR:LIM {:}"
          r: ""
          e: 'CURRENT_ERROR'
        specs:
          min: 0.0
          max: 7.0
          type: float
      voltage:
        default: 1.0
        getter:
          q: "MEAS:VOLT?"
          r: "{:.2f}"
        setter:
          q: "VOLT {:.2f}"
          r: ""
        specs:
          min: 0
          max: 30
          type: float
      output_enabled:
        default: '0'
        getter:
          q: "OUTPUT:STATE?"
          r: "{:s}"
        setter:
          q: "OUTPUT:STATE {:s}"
          r: ""
        specs:
          valid: ['0', '1', 'ON', 'OFF']
          type: str
  device 6:
    eom:
      ASRL INSTR:
        q: "\r\n"
        r: "\n"
      USB INSTR:
        q: "\r\n"
        r: "\n"
      TCPIP INSTR:
        q: "\r\n"
        r: "\n"
      TCPIP SOCKET:
        q: "\r\n"
        r: "\n"
      GPIB INSTR:
        q: "\r\n"
        r: "\n"
    error: ERROR
    dialogues:
      - q: "*IDN?"
        r: "Hewlett-Packard, ESG-D4000B, GB40050924, B.03.86"
      - q: "*OPC?"
        r: "Hewlett-Packard, ESG-D4000B, GB40050924, B.03.86"
      - q: "SYST:ERR?"
        r: "NO ERROR"
    properties:
      frequency:
        default: 1.0
        getter:
          q: "FREQ?"
          r: "{:.2f}"
        setter:
          q: "FREQ {:.2f}MHZ"
          r: ""
          e: "FREQ ERROR"
        specs:
          min: 0.0
          max: 6.0
          type: float
      amplitude:
        default: 0.0
        getter:
          q: "POW:LEV?"
          r: "{:.2f}"
        setter:
          q: "POW:LEV {:.2f}"
          r: ""
          e: "POW ERROR"
        specs:
          min: -100.0
          max: 20.0
          type: float

resources:
  ASRL1::INSTR:
    device: device 1
  USB::0x1111::0x2222::0x1234::INSTR:
    device: device 1
  TCPIP::localhost::INSTR:
    device: device 1
  TCPIP::localhost::10001::SOCKET:
    device: device 1
  GPIB::8::INSTR:
    device: device 1
  ASRL2::INSTR:
    device: device 2
  USB::0x1111::0x2222::0x2468::INSTR:
    device: device 2
  TCPIP::localhost:2222::INSTR:
    device: device 2
  GPIB::9::INSTR:
    device: device 2
  ASRL3::INSTR:
    device: device 3
  USB::0x1111::0x2222::0x3692::INSTR:
    device: device 3
  TCPIP::localhost:3333::INSTR:
    device: device 3
  GPIB::10::INSTR:
    device: device 3
  ASRL4::INSTR:
    device: device 4
  USB::0x1111::0x2222::0x4444::INSTR:
    device: device 4
  TCPIP::localhost:4444::INSTR:
    device: device 4
  GPIB::4::INSTR:
    device: device 4
  USB::0x1111::0x2222::0x4445::RAW:
    device: device 1
  GPIB0::22::INSTR:
    device: device 5
  GPIB0::2::INSTR:
    device: device 6
