spec: "1.0"
devices:
  device 1:
    eom:
      ASRL INSTR:
        q: "\r\n"
        r: "\n"
      USB INSTR:
        q: "\n"
        r: "\n"
      TCPIP INSTR:
        q: "\n"
        r: "\n"
      GPIB INSTR:
        q: "\n"
        r: "\n"
    error: ERROR
    dialogues:
      - q: "?IDN"
        r: "LSG Serial #1234"
      - q: "!CAL"
        r: OK
    properties:
      frequency:
        default: 100.0
        getter:
          q: "?FREQ"
          r: "{:.2f}"
        setter:
          q: "!FREQ {:.2f}"
          r: OK
          e: 'FREQ_ERROR'
        specs:
          min: 1
          max: 100000
          type: float
      amplitude:
        default: 1.0
        getter:
          q: "?AMP"
          r: "{:.2f}"
        setter:
          q: "!AMP {:.2f}"
          r: OK
        specs:
          min: 0
          max: 10
          type: float
      offset:
        default: 0
        getter:
          q: "?OFF"
          r: "{:.2f}"
        setter:
          q: "!OFF {:.2f}"
          r: OK
        specs:
          min: 0
          max: 10
          type: float
      output_enabled:
        default: 0
        getter:
          q: "?OUT"
          r: "{:d}"
        setter:
          q: "!OUT {:d}"
          r: OK
        specs:
          valid: [0, 1]
          type: int
      waveform:
        default: 0
        getter:
          q: "?WVF"
          r: "{:d}"
        setter:
          q: "!WVF {:d}"
          r: OK
        specs:
          valid: [0, 1, 2, 3]
          type: int
  device 2:
    eom:
      ASRL INSTR:
        q: "\r\n"
        r: "\n"
      USB INSTR:
        q: "\n"
        r: "\n"
      TCPIP INSTR:
        q: "\n"
        r: "\n"
      GPIB INSTR:
        q: "\n"
        r: "\n"
    dialogues:
      - q: "*IDN?"
        r: "SCPI,MOCK,VERSION_1.0"
    error:
      response:
        command_error: null_response
        query_error: raise VisaIOError(VI_ERROR_TMO)
      status_register:
        - q: "*ESR?"
          command_error: 32
          query_error: 4
    properties:
      voltage:
        default: 1.0
        getter:
          q: ":VOLT:IMM:AMPL?"
          r: "{:+.8E}"
        setter:
          q: ":VOLT:IMM:AMPL {:.3f}"
        specs:
          min: 1
          max: 6
          type: float
      current:
        default: 1.0
        getter:
          q: ":CURR:IMM:AMPL?"
          r: "{:+.8E}"
        setter:
          q: ":CURR:IMM:AMPL {:.3f}"
        specs:
          min: 1
          max: 6
          type: float
      rail:
        default: P6V
        getter:
          q: "INST?"
          r: "{:s}"
        setter:
          q: "INST {:s}"
        specs:
            valid: ["P6V", "P25V", "N25V"]
            type: str
      output_enabled:
        default: 0
        getter:
          q: "OUTP?"
          r: "{:d}"
        setter:
          q: "OUTP {:d}"
        specs:
          valid: [0, 1]
          type: int
  device 3:
    eom:
      ASRL INSTR:
        q: "\r\n"
        r: "\n"
      USB INSTR:
        q: "\n"
        r: "\n"
      TCPIP INSTR:
        q: "\n"
        r: "\n"
      GPIB INSTR:
        q: "\n"
        r: "\n"
    dialogues:
      - q: "*IDN?"
        r: "SCPI,MOCK,VERSION_1.0"
    error:
      response:
        query_error: 'ERROR'
      status_register:
        - q: "*ESR?"
          command_error: 32
          query_error: 4
    properties:
      voltage:
        default: 1.0
        getter:
          q: ":VOLT:IMM:AMPL?"
          r: "{:+.8E}"
        setter:
          q: ":VOLT:IMM:AMPL {:.3f}"
          e: raise VisaIOError(VI_ERROR_TMO)
        specs:
          min: 1
          max: 6
          type: float
      current:
        default: 1.0
        getter:
          q: ":CURR:IMM:AMPL?"
          r: "{:+.8E}"
        setter:
          q: ":CURR:IMM:AMPL {:.3f}"
        specs:
          min: 1
          max: 6
          type: float
      rail:
        default: P6V
        getter:
          q: "INST?"
          r: "{:s}"
        setter:
          q: "INST {:s}"
        specs:
            valid: ["P6V", "P25V", "N25V"]
            type: str
      output_enabled:
        default: 0
        getter:
          q: "OUTP?"
          r: "{:d}"
        setter:
          q: "OUTP {:d}"

resources:
  ASRL1::INSTR:
    device: device 1
  USB::0x1111::0x2222::0x1234::INSTR:
    device: device 1
  TCPIP::localhost::INSTR:
    device: device 1
  GPIB::8::INSTR:
    device: device 1
  GPIB::9::INSTR:
    device: device 2
  GPIB::10::INSTR:
    device: device 3
